cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='cart'),
    path('count/', views.count),
    path('checkout/', views.checkout, name='checkout'),
    # CRUD
    path('add/', views.add),
    path('qty/', views.quantity),
    path('deletemenu/', views.delete),
    path('deleteall/', views.deleteall),
]

deluxe/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include
from theme.views import changetheme

urlpatterns = [
    # path("admin/", admin.site.urls),
    path('', include('index.urls')),
    path('menu/', include('menu.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('news/', include('news.urls')),
    path('contact/', include('contact.urls')),
    path('users/', include('users.urls')),
    path('manager/', include('manager.urls')),
    path('changetheme/', changetheme),

]


def custom_404(request, exception):
    context = {
        'title': '404'
    }
    return render(request, 'pages/404.html', context=context, status=404)


handler404 = custom_404

news/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='news'),

    path('new/', views.add),
    path('create/', views.create),
    path('edit/<str:slug>', views.edit),
    path('update/', views.update),
    path('delete/', views.delete),

    path('<str:slug>/', views.news, name='news-detail'),
]

news/models.py
from django.db import models

# Create your models here.


class News(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField()
    author = models.CharField(max_length=50)
    image = models.URLField(max_length=200)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.title

news/forms.py
from django import forms
from django.forms import forms, Textarea, ModelForm
from .models import News
from django.template.defaultfilters import slugify


class NewsForm(ModelForm):

    class Meta:
        model = News
        exclude = ['slug']

    def clean(self):
        cleaned_data = super(NewsForm, self).clean()
        getslug = cleaned_data.get('title')
        slug = slugify(getslug)

        if News.objects.filter(slug=slug).exists():
            raise forms.ValidationError(
                "Title or content is already exists", code="")

        return cleaned_data

news/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from news.models import News
from django.core.paginator import Paginator
from django.contrib.admin.views.decorators import staff_member_required
from django.http import HttpResponse, HttpResponseNotFound
from .models import News
from django.contrib import messages
from django.template.defaultfilters import slugify
from .forms import NewsForm
# Create your views here.


def index(request):
    news = Paginator(News.objects.all().order_by('-created_at'), 4)
    page_number = request.GET.get('page')
    page_obj = news.get_page(page_number)
    context = {
        'title': "News",
        'news': page_obj
    }
    return render(request, 'news.html', context)


def news(request, slug):
    news = News.objects.filter(slug=slug).get()
    context = {
        'title': "News",
        'news': news
    }
    return render(request, 'news-detail.html', context)


@staff_member_required
def add(request):
    context = {
        'title': 'New News',
        'form': NewsForm
    }
    return render(request, 'news-add-form.html', context)


@staff_member_required
def create(request):
    if request.method == "POST":

        body = request.POST['body']

        form = NewsForm(request.POST)
        if form.is_valid():
            createnews = News(title=request.POST['title'], slug=slugify(
                request.POST['title']), author=request.POST['author'], image=request.POST['image'], body=request.POST['body'])
            createnews.save()

            if 'next' in request.POST:
                return redirect(request.POST['next'])

            return redirect('/news/')
        return render(request, 'news-add-form.html', {'title': 'New News', 'form': form, 'body': body})
    return HttpResponseNotFound(render(request, 'pages/404.html'))


@staff_member_required
def edit(request, slug):
    getnews = News.objects.filter(slug=slug).get()
    context = {
        'title': 'Edit News',
        'news': getnews
    }
    return render(request, 'news-edit-form.html', context)


@staff_member_required
def update(request):
    if request.method == "POST":
        oldslug = request.POST['slug']
        title = request.POST['title']
        slug = slugify(title)
        author = request.POST['author']
        image = request.POST['image']
        body = request.POST['body']

        getnews = News.objects.filter(slug=oldslug).get()
        getnews.title = title
        getnews.slug = slug
        getnews.author = author
        getnews.image = image
        getnews.body = body
        getnews.save()

        if 'next' in request.POST:
            return redirect(request.POST['next'])

        return redirect('/news/'+slug)
    return HttpResponseNotFound(render(request, 'pages/404.html'))


@staff_member_required
def delete(request):
    if request.method == "POST":
        slug = request.POST['news']
        getnews = News.objects.filter(slug=slug).get()
        getnews.delete()

        messages.success(request, f"{getnews.title} deleted successfully")

        if 'next' in request.POST:
            return redirect(request.POST['next'])
        return redirect('/news/')

    return HttpResponseNotFound(render(request, 'pages/404.html'))

news/templates/news-add-form.html
{% extends 'base-form.html' %}{% block content %}

<div id="news-form" class="p-3">
  {% include 'components/image-preview.html' %}
  <a onClick="javascript:history.go(-1);" class="cursor-pointer dark:text-skin"
    >Back</a
  >
  <h1
    class="mt-10 text-3xl border-b border-neutral-300 pb-2 md:text-4xl lg:text-4xl"
  >
    New News
  </h1>
  <form action="/news/create/" method="post" class="mt-10">
    {% if form.errors %}
    <p class="bg-red-500 p-1 text-neutral-100 w-fit">{{ form.errors }}</p>
    {% endif %} {% csrf_token %}
    <div class="news-input">
      <label>Title</label>
      {{ form.title }}
    </div>
    <div class="news-input">
      <label>Author</label>
      {{ form.author }}
    </div>
    <div class="news-input">
      <label>Image</label>
      {{ form.image }}
    </div>
    <div id="news-form-tiny">
      <label>Body</label>
      <textarea id="id_body" name="body">
{% if body %}{{ body }}{% endif %}</textarea
      >
    </div>

    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{ request.GET.next }}" />
    {% endif %}

    <button
      type="submit"
      class="bg-brown px-4 py-1 rounded-md text-grey md:text-lg lg:text-xl"
    >
      Create
    </button>
  </form>
</div>

{% endblock content %}

news/templates/news-detail.html
{% extends 'base.html' %} {% load humanize %} {% block content %}

<div id="news-detail" class="pt-20 p-3 mx-auto md:w-10/12 flex flex-col mb-52">
  <a
    onClick="javascript:history.go(-1);"
    class="text-right underline self-end text-lg right-0 cursor-pointer"
    >Back</a
  >

  <h1 class="text-2xl md:text-3xl lg:text-4xl mt-5">{{ news.title }}</h1>
  <p class="text-[11px] text-neutral-500 flex">
    By {{ news.author }} at {{ news.created_at | timesince}} ago
    <!-- -->
    {% if user.is_staff %}
    <a href="/news/edit/{{ news.slug }}" class="text-right">
      <span
        class="material-symbols-rounded ml-3 text-brown text-[20px] md:text-xl lg:text-2xl"
      >
        edit
      </span></a
    >
    {% endif %}
  </p>
  <img
    class="mx-auto h-[22vh] mt-5 w-10/12 object-cover mb-7"
    src="{{ news.image }}"
  />
  {% autoescape off %} {{ news.body}} {% endautoescape %}
</div>

{% endblock %}

news/templates/news-edit-form.html
{% extends 'base-form.html' %}{% block content %}

<div id="news-form" class="p-3">
  {% include 'components/image-preview.html' %}
  <a onClick="javascript:history.go(-1);" class="cursor-pointer dark:text-skin">Back</a>
  <h1
    class="mt-10 text-3xl md:text-4xl lg:text-4xl border-b border-neutral-300 pb-2"
  >
    Edit News
  </h1>

  <form action="/news/update/" method="post">
    {% csrf_token %}
    <div class="news-input">
      <label>Title</label>
      <input type="text" name="title" value="{{ news.title }}" required />
    </div>
    <div class="news-input">
      <label>Author</label>
      <input type="text" name="author" value="{{ news.author }}" />
    </div>
    <div class="news-input">
      <label>Image</label>
      <input type="text" name="image" value="{{ news.image }}" id="id_image" />
    </div>
    <div id="news-form-tiny">
      <label>Body</label>
      <input id="b" name="body" type="hidden" />
      <textarea id="id_body" name="body">{{ news.body }}</textarea>
    </div>

    <input type="hidden" name="slug" value="{{ news.slug }}" />

    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{ request.GET.next }}" />
    {% endif %}

    <button type="submit" class="bg-brown px-4 py-1 rounded-md text-grey">
      Update
    </button>
  </form>

  <div class="mt-16">
    <form id="form-delete-news" action="/news/delete/" method="post">
      {% csrf_token %}
    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{ request.GET.next }}"></input>
    {% endif %}
    <input type="hidden" name="news" value="{{ news.slug }}"></input>
    <button type="submit" id="delete-news-btn" class="cursor-pointer px-5 py-2 border border-red-500 text-red-500 rounded-md"
      >Delete</button>
  </div>
</div>

{% endblock content %}

news/templates/news.html
{% extends 'base.html' %} {% block content %}

<div id="news" class="pt-24 p-3 mb-22">
  <h1 class="text-6xl font-monte">News</h1>

  <!-- FOR STAFF -->
  {% if user.is_staff %}
  <a
    href="/news/new/"
    class="float-right text-sm md:text-base lg:text-lg bg-brown px-5 py-2 text-grey rounded-md"
    >+News</a
  {% endif %}

  <div id="news-container" class="mt-12 clean-both">
    {% for n in news %}
    <div
      class="news h-[43vh] w-10/12 my-10 sm:w-8/12 lg:w-6/12 mx-auto border-b border-orange"
      data-aos="fade-up"
    >
      <img class="h-1/2 w-full object-cover rounded-t-md" src="{{ n.image }}" />
      <div id="news-description">
        <h3 class="bg-brown text-grey p-1 md:text-xl">{{ n.title }}</h3>
        <p
          class="text-[12px] lg:text-md my-3 text-neutral-600 break-all dark:text-neutral-200 w-10/12"
        >
          {{ n.body | striptags | truncatechars:"50" }}
        </p>
        <a
          class="mt-4 border border-brown px-2 py-1 rounded-md text-[12px] md:text-sm"
          href="/news/{{ n.slug }}"
          >Read more...</a
        >
      </div>
    </div>
    {% endfor %}
  </div>

  <div
    id="news-paginator"
    class="mt-16 flex justify-evenly text-sm items-center"
  >
    {% if news.has_previous %}
    <a
      href="?page={{ news.previous_page_number }}"
      class="text-neutral-700 dark:text-neutral-300"
      >Previous</a
    >
    {% else %}
    <p>-</p>
    {% endif %}
    <p>{{ news.number }} of {{ news.paginator.num_pages }}</p>
    {% if news.has_next %}
    <a
      href="?page={{ news.next_page_number }}"
      class="p-3 hover:bg-neutral-200 rounded-md transition duration-300 ease-in-out dark:hover:bg-tree"
      >Next></a
    >
    {% else %}
    <p>-</p>
    {% endif %}
  </div>
</div>

{% endblock %}